# Generated by Django 2.1 on 2018-08-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pseud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseud_name', models.CharField(max_length=100, verbose_name='pseud name')),
            ],
        ),
    ]
