# Generated by Django 2.0.3 on 2018-03-20 01:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(max_length=200, verbose_name='work title')),
                ('work_summary', models.TextField(max_length=500, verbose_name='work summary')),
                ('date_created', models.DateField(default=datetime.date.today, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_part_title', models.CharField(max_length=200, verbose_name='work part title')),
                ('work_part_text', models.TextField(verbose_name='work part text')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanarchive.Work')),
            ],
        ),
    ]
