# Generated by Django 2.1 on 2018-08-21 23:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Fic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fic_title', models.CharField(max_length=200, verbose_name='fic title')),
                ('fic_summary', models.TextField(max_length=500, verbose_name='fic summary')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated')),
                ('fic_author_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanfic.AuthorGroup')),
            ],
        ),
        migrations.CreateModel(
            name='FicPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fic_part_title', models.CharField(max_length=200, verbose_name='fic part title')),
                ('fic_part_text', models.TextField(verbose_name='fic part text')),
                ('fic_part_number', models.PositiveIntegerField(null=True, verbose_name='fic part number')),
                ('fic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanfic.Fic')),
            ],
        ),
    ]
