# Generated by Django 2.1.3 on 2018-12-01 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fanfic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pseud',
            name='pseud_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ficpart',
            name='fic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanfic.Fic', verbose_name='fic'),
        ),
        migrations.AddField(
            model_name='fic',
            name='fic_author_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanfic.AuthorGroup', verbose_name='fic author(s)'),
        ),
        migrations.AddField(
            model_name='authorship',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanfic.Pseud'),
        ),
        migrations.AddField(
            model_name='authorship',
            name='author_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanfic.AuthorGroup'),
        ),
        migrations.AddField(
            model_name='authorgroup',
            name='authors',
            field=models.ManyToManyField(through='fanfic.Authorship', to='fanfic.Pseud'),
        ),
        migrations.AlterUniqueTogether(
            name='authorship',
            unique_together={('author_group', 'author')},
        ),
    ]
