# Generated by Django 2.1 on 2018-08-21 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pseuds', '0001_initial'),
        ('fanfic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorship',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pseuds.Pseud'),
        ),
        migrations.AddField(
            model_name='authorship',
            name='author_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanfic.AuthorGroup'),
        ),
        migrations.AddField(
            model_name='authorgroup',
            name='authors',
            field=models.ManyToManyField(through='fanfic.Authorship', to='pseuds.Pseud'),
        ),
    ]
