# Generated by Django 2.1 on 2018-08-22 02:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fanfic', '0002_auto_20180822_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficpart',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated'),
        ),
        migrations.AddField(
            model_name='ficpart',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='pseud',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='fic',
            name='fic_author_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanfic.AuthorGroup', verbose_name='fic author(s)'),
        ),
        migrations.AlterField(
            model_name='ficpart',
            name='fic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanfic.Fic', verbose_name='fic'),
        ),
        migrations.AlterField(
            model_name='pseud',
            name='pseud_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='pseud name'),
        ),
    ]
