# Generated by Django 2.1 on 2018-08-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfic', '0002_auto_20180822_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fic',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='ficpart',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
    ]
