# Generated by Django 2.1 on 2018-08-25 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanfic', '0003_auto_20180822_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='PseudGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='group name')),
            ],
        ),
        migrations.CreateModel(
            name='PseudInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanfic.Pseud', verbose_name='pseud')),
            ],
        ),
        migrations.AddField(
            model_name='pseudgroup',
            name='authors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanfic.PseudInstance', verbose_name='authors'),
        ),
    ]
