# Generated by Django 2.1 on 2018-08-25 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanfic', '0004_auto_20180825_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pseudgroup',
            name='authors',
        ),
        migrations.AddField(
            model_name='pseudinstance',
            name='pseud_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fanfic.PseudGroup'),
            preserve_default=False,
        ),
    ]
