# Generated by Django 2.1 on 2018-08-25 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanfic', '0005_auto_20180825_2111'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authorship',
            unique_together={('author_group', 'author')},
        ),
    ]
