# Generated by Django 2.1 on 2018-08-25 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanfic', '0006_auto_20180825_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pseudinstance',
            name='pseud',
        ),
        migrations.RemoveField(
            model_name='pseudinstance',
            name='pseud_group',
        ),
        migrations.DeleteModel(
            name='PseudGroup',
        ),
        migrations.DeleteModel(
            name='PseudInstance',
        ),
    ]
