# Generated by Django 2.0.3 on 2018-03-20 01:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fic_title', models.CharField(max_length=200, verbose_name='fic title')),
                ('fic_summary', models.TextField(max_length=500, verbose_name='fic summary')),
                ('date_created', models.DateField(default=datetime.date.today, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='FicPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fic_part_title', models.CharField(max_length=200, verbose_name='fic part title')),
                ('fic_part_text', models.TextField(verbose_name='fic part text')),
                ('fic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanarchive.Fic')),
            ],
        ),
    ]
