# Generated by Django 2.0.3 on 2018-04-07 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fanarchive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fic',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated'),
        ),
        migrations.AddField(
            model_name='fic',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
    ]
