# Generated by Django 2.0.3 on 2018-04-07 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fanarchive', '0003_remove_fic_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fic',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
