# Generated by Django 2.0.3 on 2018-05-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanarchive', '0004_auto_20180407_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficpart',
            name='fic_part_number',
            field=models.PositiveIntegerField(null=True, verbose_name='fic part number'),
        ),
    ]
